
import UI.Principal;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JRadioButton;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

public class Falso_Verdadero extends javax.swing.JInternalFrame implements I_Controlador{
    /**
     * Creates new form Falso_Verdadero
     */
    private Principal Instacia;
    private int IDexamen;
    private int IDsecccion;
    private int IDpregunta;
    public Falso_Verdadero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        jLabel1.setText("jLabel1");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Falso");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Verdadero");

        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1)
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                    try{
                if(Instacia.Get_Preguntas_size(IDexamen, IDsecccion)>IDpregunta){
                    Instacia.SET_Pregunta_Evaluada(IDexamen,IDsecccion,IDpregunta,get_seleccion(),true);
                    if(Instacia.Get_Preguntas_size(IDexamen, IDsecccion)> (IDpregunta+1)){
                        IDpregunta+=1;
                        jSpinner1.setValue(IDpregunta);
                    }
                    else if(jButton1.getText().compareTo("Finalizar")==0){
                        this.setVisible(false);
                    }
                    else
                    {
                        jButton1.setText("Finalizar");
                    }
                }
            }
            catch(Exception er){} 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
                if(Integer.parseInt(jSpinner1.getValue().toString()) >-1)
        {
            IDpregunta=Integer.parseInt(jSpinner1.getValue().toString());
            try{
            if((Instacia.GET_Respuestas_Size(IDexamen, IDsecccion, IDpregunta)>-1)&&(IDpregunta > -1))
            {
                try{
                    jLabel1.setText(Instacia.Get_pregunta(IDexamen, IDsecccion, IDpregunta));
                }catch(Exception er){}
                try{
                    jRadioButton1.setText(Instacia.get_Respuestas(IDexamen, IDsecccion, IDpregunta).getValueAt(0, 1).toString());                
                }catch(Exception er){}
                try{
                    jRadioButton2.setText(Instacia.get_Respuestas(IDexamen, IDsecccion, IDpregunta).getValueAt(1, 1).toString());
                }catch(Exception er){}
            }
        }catch(Exception er){} 
        }
    }//GEN-LAST:event_jSpinner1StateChanged

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        if(IDpregunta>-1)
        {
            jSpinner1.setValue(IDpregunta);
            jSpinner1StateChanged(null);
        }
        else
        {
            jSpinner1.setValue(0);
            jSpinner1StateChanged(null);            
        }
    }//GEN-LAST:event_formInternalFrameOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables

    int get_seleccion(){
        int result=-1;int tresult=-1;
        Enumeration<AbstractButton> allRadioButton=buttonGroup1.getElements();
        while(allRadioButton.hasMoreElements()){
            JRadioButton temp=(JRadioButton)allRadioButton.nextElement();
            tresult++;
            if(temp.isSelected())  
            {  
                result=tresult;
            }
        }
        return result;
    }
    
    @Override
    public void Set_datos(Principal controlador, int IDexaman, int IDseccion, int IDpregunta) {
      this.Instacia=controlador;
      this.IDexamen=IDexaman;
      this.IDsecccion=IDseccion;
      this.IDpregunta=IDpregunta;
      this.setVisible(true);
    }
}
